//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtonVPN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenvpnConfigEtag {
            get {
                return ((string)(this["OpenvpnConfigEtag"]));
            }
            set {
                this["OpenvpnConfigEtag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string OvpnProtocol {
            get {
                return ((string)(this["OvpnProtocol"]));
            }
            set {
                this["OvpnProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartOnStartup {
            get {
                return ((bool)(this["StartOnStartup"]));
            }
            set {
                this["StartOnStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public string StartMinimized {
            get {
                return ((string)(this["StartMinimized"]));
            }
            set {
                this["StartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDnsLeakProtection {
            get {
                return ((bool)(this["UseDnsLeakProtection"]));
            }
            set {
                this["UseDnsLeakProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Profiles {
            get {
                return ((string)(this["Profiles"]));
            }
            set {
                this["Profiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SecureCore {
            get {
                return ((bool)(this["SecureCore"]));
            }
            set {
                this["SecureCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoConnect {
            get {
                return ((string)(this["AutoConnect"]));
            }
            set {
                this["AutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AppFirstRun {
            get {
                return ((bool)(this["AppFirstRun"]));
            }
            set {
                this["AppFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DeviceId {
            get {
                return ((string)(this["DeviceId"]));
            }
            set {
                this["DeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccessToken {
            get {
                return ((string)(this["AccessToken"]));
            }
            set {
                this["AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RefreshToken {
            get {
                return ((string)(this["RefreshToken"]));
            }
            set {
                this["RefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Uid {
            get {
                return ((string)(this["Uid"]));
            }
            set {
                this["Uid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ProtonVPN.Core.Native.Structures.WindowPlacement WindowPlacement {
            get {
                return ((global::ProtonVPN.Core.Native.Structures.WindowPlacement)(this["WindowPlacement"]));
            }
            set {
                this["WindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomDns {
            get {
                return ((bool)(this["UseCustomDns"]));
            }
            set {
                this["UseCustomDns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KillSwitch {
            get {
                return ((bool)(this["KillSwitch"]));
            }
            set {
                this["KillSwitch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SidebarMode {
            get {
                return ((bool)(this["SidebarMode"]));
            }
            set {
                this["SidebarMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Width {
            get {
                return ((double)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Ip {
            get {
                return ((string)(this["Ip"]));
            }
            set {
                this["Ip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Latitude {
            get {
                return ((string)(this["Latitude"]));
            }
            set {
                this["Latitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Longitude {
            get {
                return ((string)(this["Longitude"]));
            }
            set {
                this["Longitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotifications {
            get {
                return ((bool)(this["ShowNotifications"]));
            }
            set {
                this["ShowNotifications"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.3")]
        public string ServerApiVersion {
            get {
                return ((string)(this["ServerApiVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ProtonVPN.Core.Native.Structures.WindowPlacement SidebarWindowPlacement {
            get {
                return ((global::ProtonVPN.Core.Native.Structures.WindowPlacement)(this["SidebarWindowPlacement"]));
            }
            set {
                this["SidebarWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Isp {
            get {
                return ((string)(this["Isp"]));
            }
            set {
                this["Isp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Country {
            get {
                return ((string)(this["Country"]));
            }
            set {
                this["Country"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUpdate {
            get {
                return ((string)(this["LastUpdate"]));
            }
            set {
                this["LastUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VpnPlanName {
            get {
                return ((string)(this["VpnPlanName"]));
            }
            set {
                this["VpnPlanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VpnPlan {
            get {
                return ((string)(this["VpnPlan"]));
            }
            set {
                this["VpnPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public sbyte MaxTier {
            get {
                return ((sbyte)(this["MaxTier"]));
            }
            set {
                this["MaxTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Delinquent {
            get {
                return ((int)(this["Delinquent"]));
            }
            set {
                this["Delinquent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxConnect {
            get {
                return ((int)(this["MaxConnect"]));
            }
            set {
                this["MaxConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Services {
            get {
                return ((int)(this["Services"]));
            }
            set {
                this["Services"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QuickConnect {
            get {
                return ((string)(this["QuickConnect"]));
            }
            set {
                this["QuickConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EarlyAccess {
            get {
                return ((bool)(this["EarlyAccess"]));
            }
            set {
                this["EarlyAccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WelcomeModalShown {
            get {
                return ((bool)(this["WelcomeModalShown"]));
            }
            set {
                this["WelcomeModalShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OnboardingStep {
            get {
                return ((int)(this["OnboardingStep"]));
            }
            set {
                this["OnboardingStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AppStartCounter {
            get {
                return ((int)(this["AppStartCounter"]));
            }
            set {
                this["AppStartCounter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SidebarTab {
            get {
                return ((int)(this["SidebarTab"]));
            }
            set {
                this["SidebarTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitTunnelingBlockApps {
            get {
                return ((string)(this["SplitTunnelingBlockApps"]));
            }
            set {
                this["SplitTunnelingBlockApps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitTunnelExcludeIps {
            get {
                return ((string)(this["SplitTunnelExcludeIps"]));
            }
            set {
                this["SplitTunnelExcludeIps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SettingsSelectedTabIndex {
            get {
                return ((int)(this["SettingsSelectedTabIndex"]));
            }
            set {
                this["SettingsSelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SplitTunnelingEnabled {
            get {
                return ((bool)(this["SplitTunnelingEnabled"]));
            }
            set {
                this["SplitTunnelingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string SplitTunnelMode {
            get {
                return ((string)(this["SplitTunnelMode"]));
            }
            set {
                this["SplitTunnelMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitTunnelingAllowApps {
            get {
                return ((string)(this["SplitTunnelingAllowApps"]));
            }
            set {
                this["SplitTunnelingAllowApps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserSettingsMigrated {
            get {
                return ((bool)(this["UserSettingsMigrated"]));
            }
            set {
                this["UserSettingsMigrated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserSettingsVersion {
            get {
                return ((string)(this["UserSettingsVersion"]));
            }
            set {
                this["UserSettingsVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserProfiles {
            get {
                return ((string)(this["UserProfiles"]));
            }
            set {
                this["UserProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserQuickConnect {
            get {
                return ((string)(this["UserQuickConnect"]));
            }
            set {
                this["UserQuickConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAutoConnect {
            get {
                return ((string)(this["UserAutoConnect"]));
            }
            set {
                this["UserAutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserUid {
            get {
                return ((string)(this["UserUid"]));
            }
            set {
                this["UserUid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAccessToken {
            get {
                return ((string)(this["UserAccessToken"]));
            }
            set {
                this["UserAccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserRefreshToken {
            get {
                return ((string)(this["UserRefreshToken"]));
            }
            set {
                this["UserRefreshToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserVpnPlan {
            get {
                return ((string)(this["UserVpnPlan"]));
            }
            set {
                this["UserVpnPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserMaxTier {
            get {
                return ((string)(this["UserMaxTier"]));
            }
            set {
                this["UserMaxTier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDelinquent {
            get {
                return ((string)(this["UserDelinquent"]));
            }
            set {
                this["UserDelinquent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserMaxConnect {
            get {
                return ((string)(this["UserMaxConnect"]));
            }
            set {
                this["UserMaxConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserServices {
            get {
                return ((string)(this["UserServices"]));
            }
            set {
                this["UserServices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserVpnPlanName {
            get {
                return ((string)(this["UserVpnPlanName"]));
            }
            set {
                this["UserVpnPlanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserWelcomeModalShown {
            get {
                return ((string)(this["UserWelcomeModalShown"]));
            }
            set {
                this["UserWelcomeModalShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserOnboardingStep {
            get {
                return ((string)(this["UserOnboardingStep"]));
            }
            set {
                this["UserOnboardingStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserProfileChangesSyncedAt {
            get {
                return ((string)(this["UserProfileChangesSyncedAt"]));
            }
            set {
                this["UserProfileChangesSyncedAt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserSecureCore {
            get {
                return ((string)(this["UserSecureCore"]));
            }
            set {
                this["UserSecureCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Ipv6LeakProtection {
            get {
                return ((bool)(this["Ipv6LeakProtection"]));
            }
            set {
                this["Ipv6LeakProtection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomDnsEnabled {
            get {
                return ((bool)(this["CustomDnsEnabled"]));
            }
            set {
                this["CustomDnsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomDnsIps {
            get {
                return ((string)(this["CustomDnsIps"]));
            }
            set {
                this["CustomDnsIps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCustomDnsEnabled {
            get {
                return ((string)(this["UserCustomDnsEnabled"]));
            }
            set {
                this["UserCustomDnsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCustomDnsIps {
            get {
                return ((string)(this["UserCustomDnsIps"]));
            }
            set {
                this["UserCustomDnsIps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserNetShieldMode {
            get {
                return ((string)(this["UserNetShieldMode"]));
            }
            set {
                this["UserNetShieldMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserNetShieldEnabled {
            get {
                return ((string)(this["UserNetShieldEnabled"]));
            }
            set {
                this["UserNetShieldEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SettingsVersion {
            get {
                return ((string)(this["SettingsVersion"]));
            }
            set {
                this["SettingsVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AlternativeApiBaseUrls {
            get {
                return ((string)(this["AlternativeApiBaseUrls"]));
            }
            set {
                this["AlternativeApiBaseUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveAlternativeApiBaseUrl {
            get {
                return ((string)(this["ActiveAlternativeApiBaseUrl"]));
            }
            set {
                this["ActiveAlternativeApiBaseUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DoHEnabled {
            get {
                return ((bool)(this["DoHEnabled"]));
            }
            set {
                this["DoHEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitTunnelIncludeIps {
            get {
                return ((string)(this["SplitTunnelIncludeIps"]));
            }
            set {
                this["SplitTunnelIncludeIps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitTunnelingIps {
            get {
                return ((string)(this["SplitTunnelingIps"]));
            }
            set {
                this["SplitTunnelingIps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAnnouncements {
            get {
                return ((string)(this["UserAnnouncements"]));
            }
            set {
                this["UserAnnouncements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenVpnTcpPorts {
            get {
                return ((string)(this["OpenVpnTcpPorts"]));
            }
            set {
                this["OpenVpnTcpPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OpenVpnUdpPorts {
            get {
                return ((string)(this["OpenVpnUdpPorts"]));
            }
            set {
                this["OpenVpnUdpPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeatureNetShieldEnabled {
            get {
                return ((bool)(this["FeatureNetShieldEnabled"]));
            }
            set {
                this["FeatureNetShieldEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FeatureMaintenanceTrackerEnabled {
            get {
                return ((bool)(this["FeatureMaintenanceTrackerEnabled"]));
            }
            set {
                this["FeatureMaintenanceTrackerEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeaturePollNotificationApiEnabled {
            get {
                return ((bool)(this["FeaturePollNotificationApiEnabled"]));
            }
            set {
                this["FeaturePollNotificationApiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan MaintenanceCheckInterval {
            get {
                return ((global::System.TimeSpan)(this["MaintenanceCheckInterval"]));
            }
            set {
                this["MaintenanceCheckInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UserNetShieldEnabledDefault {
            get {
                return ((bool)(this["UserNetShieldEnabledDefault"]));
            }
            set {
                this["UserNetShieldEnabledDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int UserNetShieldModeDefault {
            get {
                return ((int)(this["UserNetShieldModeDefault"]));
            }
            set {
                this["UserNetShieldModeDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NetworkAdapterType {
            get {
                return ((string)(this["NetworkAdapterType"]));
            }
            set {
                this["NetworkAdapterType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPortForwardingEnabled {
            get {
                return ((string)(this["UserPortForwardingEnabled"]));
            }
            set {
                this["UserPortForwardingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeaturePortForwardingEnabled {
            get {
                return ((bool)(this["FeaturePortForwardingEnabled"]));
            }
            set {
                this["FeaturePortForwardingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoNotShowPortForwardingConfirmationDialog {
            get {
                return ((bool)(this["DoNotShowPortForwardingConfirmationDialog"]));
            }
            set {
                this["DoNotShowPortForwardingConfirmationDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PortForwardingNotificationsEnabled {
            get {
                return ((bool)(this["PortForwardingNotificationsEnabled"]));
            }
            set {
                this["PortForwardingNotificationsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PortForwardingInQuickSettings {
            get {
                return ((bool)(this["PortForwardingInQuickSettings"]));
            }
            set {
                this["PortForwardingInQuickSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string KillSwitchMode {
            get {
                return ((string)(this["KillSwitchMode"]));
            }
            set {
                this["KillSwitchMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDoNotShowKillSwitchConfirmationDialog {
            get {
                return ((string)(this["UserDoNotShowKillSwitchConfirmationDialog"]));
            }
            set {
                this["UserDoNotShowKillSwitchConfirmationDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDoNotShowEnableSmartProtocolDialog {
            get {
                return ((string)(this["UserDoNotShowEnableSmartProtocolDialog"]));
            }
            set {
                this["UserDoNotShowEnableSmartProtocolDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VpnAcceleratorEnabled {
            get {
                return ((bool)(this["VpnAcceleratorEnabled"]));
            }
            set {
                this["VpnAcceleratorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FeatureVpnAcceleratorEnabled {
            get {
                return ((bool)(this["FeatureVpnAcceleratorEnabled"]));
            }
            set {
                this["FeatureVpnAcceleratorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeatureStreamingServicesLogosEnabled {
            get {
                return ((bool)(this["FeatureStreamingServicesLogosEnabled"]));
            }
            set {
                this["FeatureStreamingServicesLogosEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FeatureSmartReconnectEnabled {
            get {
                return ((bool)(this["FeatureSmartReconnectEnabled"]));
            }
            set {
                this["FeatureSmartReconnectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmartReconnectEnabled {
            get {
                return ((bool)(this["SmartReconnectEnabled"]));
            }
            set {
                this["SmartReconnectEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SmartReconnectNotificationsEnabled {
            get {
                return ((bool)(this["SmartReconnectNotificationsEnabled"]));
            }
            set {
                this["SmartReconnectNotificationsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAuthenticationPublicKey {
            get {
                return ((string)(this["UserAuthenticationPublicKey"]));
            }
            set {
                this["UserAuthenticationPublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAuthenticationSecretKey {
            get {
                return ((string)(this["UserAuthenticationSecretKey"]));
            }
            set {
                this["UserAuthenticationSecretKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAuthenticationCertificatePem {
            get {
                return ((string)(this["UserAuthenticationCertificatePem"]));
            }
            set {
                this["UserAuthenticationCertificatePem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAuthenticationCertificateExpirationUtcDate {
            get {
                return ((string)(this["UserAuthenticationCertificateExpirationUtcDate"]));
            }
            set {
                this["UserAuthenticationCertificateExpirationUtcDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAuthenticationCertificateRefreshUtcDate {
            get {
                return ((string)(this["UserAuthenticationCertificateRefreshUtcDate"]));
            }
            set {
                this["UserAuthenticationCertificateRefreshUtcDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAuthenticationCertificateRequestUtcDate {
            get {
                return ((string)(this["UserAuthenticationCertificateRequestUtcDate"]));
            }
            set {
                this["UserAuthenticationCertificateRequestUtcDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCertificationServerPublicKey {
            get {
                return ((string)(this["UserCertificationServerPublicKey"]));
            }
            set {
                this["UserCertificationServerPublicKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseTunAdapter {
            get {
                return ((bool)(this["UseTunAdapter"]));
            }
            set {
                this["UseTunAdapter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WireGuardPorts {
            get {
                return ((string)(this["WireGuardPorts"]));
            }
            set {
                this["WireGuardPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeatureSmartProtocolWireGuardEnabled {
            get {
                return ((bool)(this["FeatureSmartProtocolWireGuardEnabled"]));
            }
            set {
                this["FeatureSmartProtocolWireGuardEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HardwareAccelerationEnabled {
            get {
                return ((bool)(this["HardwareAccelerationEnabled"]));
            }
            set {
                this["HardwareAccelerationEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserReportAnIssueFormData {
            get {
                return ((string)(this["UserReportAnIssueFormData"]));
            }
            set {
                this["UserReportAnIssueFormData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserDoNotShowDiscourageSecureCoreDialog {
            get {
                return ((string)(this["UserDoNotShowDiscourageSecureCoreDialog"]));
            }
            set {
                this["UserDoNotShowDiscourageSecureCoreDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserAllowNonStandardPorts {
            get {
                return ((string)(this["UserAllowNonStandardPorts"]));
            }
            set {
                this["UserAllowNonStandardPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserAllowNonStandardPortsDefault {
            get {
                return ((bool)(this["UserAllowNonStandardPortsDefault"]));
            }
            set {
                this["UserAllowNonStandardPortsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowNonStandardPortsToFreeUsers {
            get {
                return ((bool)(this["ShowNonStandardPortsToFreeUsers"]));
            }
            set {
                this["ShowNonStandardPortsToFreeUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserModerateNat {
            get {
                return ((string)(this["UserModerateNat"]));
            }
            set {
                this["UserModerateNat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ConnectOnAppStart {
            get {
                return ((bool)(this["ConnectOnAppStart"]));
            }
            set {
                this["ConnectOnAppStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartOnBoot {
            get {
                return ((bool)(this["StartOnBoot"]));
            }
            set {
                this["StartOnBoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCredit {
            get {
                return ((string)(this["UserCredit"]));
            }
            set {
                this["UserCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserSubscribed {
            get {
                return ((string)(this["UserSubscribed"]));
            }
            set {
                this["UserSubscribed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserHasPaymentMethod {
            get {
                return ((string)(this["UserHasPaymentMethod"]));
            }
            set {
                this["UserHasPaymentMethod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeaturePromoCodeEnabled {
            get {
                return ((bool)(this["FeaturePromoCodeEnabled"]));
            }
            set {
                this["FeaturePromoCodeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsToShowRebrandingPopup {
            get {
                return ((bool)(this["IsToShowRebrandingPopup"]));
            }
            set {
                this["IsToShowRebrandingPopup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DnsCache {
            get {
                return ((string)(this["DnsCache"]));
            }
            set {
                this["DnsCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsToAutoUpdate {
            get {
                return ((bool)(this["IsToAutoUpdate"]));
            }
            set {
                this["IsToAutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FeatureNetShieldStatsEnabled {
            get {
                return ((bool)(this["FeatureNetShieldStatsEnabled"]));
            }
            set {
                this["FeatureNetShieldStatsEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FeatureFreeRescopeEnabled {
            get {
                return ((bool)(this["FeatureFreeRescopeEnabled"]));
            }
            set {
                this["FeatureFreeRescopeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserIsFreeRescopeModalDisplayed {
            get {
                return ((string)(this["UserIsFreeRescopeModalDisplayed"]));
            }
            set {
                this["UserIsFreeRescopeModalDisplayed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserChangeServerAttempts {
            get {
                return ((string)(this["UserChangeServerAttempts"]));
            }
            set {
                this["UserChangeServerAttempts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ChangeServerAttemptLimit {
            get {
                return ((int)(this["ChangeServerAttemptLimit"]));
            }
            set {
                this["ChangeServerAttemptLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int UserChangeServerAttemptsDefault {
            get {
                return ((int)(this["UserChangeServerAttemptsDefault"]));
            }
            set {
                this["UserChangeServerAttemptsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserNextChangeServerTimeUtc {
            get {
                return ((string)(this["UserNextChangeServerTimeUtc"]));
            }
            set {
                this["UserNextChangeServerTimeUtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int ChangeServerShortDelayInSeconds {
            get {
                return ((int)(this["ChangeServerShortDelayInSeconds"]));
            }
            set {
                this["ChangeServerShortDelayInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200")]
        public int ChangeServerLongDelayInSeconds {
            get {
                return ((int)(this["ChangeServerLongDelayInSeconds"]));
            }
            set {
                this["ChangeServerLongDelayInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTelemetryGloballyEnabled {
            get {
                return ((bool)(this["IsTelemetryGloballyEnabled"]));
            }
            set {
                this["IsTelemetryGloballyEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-01-01")]
        public global::System.DateTime LastPrimaryApiFailDateUtc {
            get {
                return ((global::System.DateTime)(this["LastPrimaryApiFailDateUtc"]));
            }
            set {
                this["LastPrimaryApiFailDateUtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserCreationDateUtc {
            get {
                return ((string)(this["UserCreationDateUtc"]));
            }
            set {
                this["UserCreationDateUtc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserStatisticalEvents {
            get {
                return ((string)(this["UserStatisticalEvents"]));
            }
            set {
                this["UserStatisticalEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FeatureFlags {
            get {
                return ((string)(this["FeatureFlags"]));
            }
            set {
                this["FeatureFlags"] = value;
            }
        }
    }
}
