//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtonVPN.Resource.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtonVPN.Resource.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربى.
        /// </summary>
        internal static string Language_ar {
            get {
                return ResourceManager.GetString("Language_ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Català.
        /// </summary>
        internal static string Language_ca {
            get {
                return ResourceManager.GetString("Language_ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čeština.
        /// </summary>
        internal static string Language_cs_CZ {
            get {
                return ResourceManager.GetString("Language_cs-CZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string Language_de_DE {
            get {
                return ResourceManager.GetString("Language_de-DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language_en_US {
            get {
                return ResourceManager.GetString("Language_en-US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latinoamérica.
        /// </summary>
        internal static string Language_es_419 {
            get {
                return ResourceManager.GetString("Language_es-419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español, España.
        /// </summary>
        internal static string Language_es_ES {
            get {
                return ResourceManager.GetString("Language_es-ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español, México.
        /// </summary>
        internal static string Language_es_MX {
            get {
                return ResourceManager.GetString("Language_es-MX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        internal static string Language_fa_IR {
            get {
                return ResourceManager.GetString("Language_fa-IR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string Language_fr_FR {
            get {
                return ResourceManager.GetString("Language_fr-FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hrvatski.
        /// </summary>
        internal static string Language_hr_HR {
            get {
                return ResourceManager.GetString("Language_hr-HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magyar.
        /// </summary>
        internal static string Language_hu_HU {
            get {
                return ResourceManager.GetString("Language_hu-HU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bahasa, Indonesia.
        /// </summary>
        internal static string Language_id_ID {
            get {
                return ResourceManager.GetString("Language_id-ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string Language_it_IT {
            get {
                return ResourceManager.GetString("Language_it-IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本人.
        /// </summary>
        internal static string Language_ja_JP {
            get {
                return ResourceManager.GetString("Language_ja-JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lietuvių.
        /// </summary>
        internal static string Language_lt_LT {
            get {
                return ResourceManager.GetString("Language_lt-LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string Language_nl_NL {
            get {
                return ResourceManager.GetString("Language_nl-NL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        internal static string Language_pl_PL {
            get {
                return ResourceManager.GetString("Language_pl-PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português, Brazil.
        /// </summary>
        internal static string Language_pt_BR {
            get {
                return ResourceManager.GetString("Language_pt-BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português, Portugal.
        /// </summary>
        internal static string Language_pt_PT {
            get {
                return ResourceManager.GetString("Language_pt-PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Română.
        /// </summary>
        internal static string Language_ro_RO {
            get {
                return ResourceManager.GetString("Language_ro-RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string Language_ru_RU {
            get {
                return ResourceManager.GetString("Language_ru-RU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string Language_tr_TR {
            get {
                return ResourceManager.GetString("Language_tr-TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Украї́нська.
        /// </summary>
        internal static string Language_uk_UA {
            get {
                return ResourceManager.GetString("Language_uk-UA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string Language_zh_CN {
            get {
                return ResourceManager.GetString("Language_zh-CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁體中文.
        /// </summary>
        internal static string Language_zh_TW {
            get {
                return ResourceManager.GetString("Language_zh-TW", resourceCulture);
            }
        }
    }
}
